//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icebreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был бы рад пообщаться с вами побольше, но дела заждались :) Увидимся на следующей неделе!.
        /// </summary>
        internal static string ByeReplyText {
            get {
                return ResourceManager.GetString("ByeReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поприветствовать {0}.
        /// </summary>
        internal static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка. Повторите попытку..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то не сложилось. Поделитесь развернутым комментарием?.
        /// </summary>
        internal static string FeedBackNoAnotherReplyText {
            get {
                return ResourceManager.GetString("FeedBackNoAnotherReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Другое.
        /// </summary>
        internal static string FeedBackNoAnswerAnother {
            get {
                return ResourceManager.GetString("FeedBackNoAnswerAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось выбрать свободное время.
        /// </summary>
        internal static string FeedBackNoAnswerNoGoodTime {
            get {
                return ResourceManager.GetString("FeedBackNoAnswerNoGoodTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собеседник не ответил.
        /// </summary>
        internal static string FeedBackNoAnswerNoResponse {
            get {
                return ResourceManager.GetString("FeedBackNoAnswerNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как грустно это слышать. Раскажете, почему?.
        /// </summary>
        internal static string FeedBackNoAnswerRequestText {
            get {
                return ResourceManager.GetString("FeedBackNoAnswerRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое случается. Поделитесь развернутым комментарием?.
        /// </summary>
        internal static string FeedBackNoCanceledReplyText {
            get {
                return ResourceManager.GetString("FeedBackNoCanceledReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какая досада. Но вы не огорчайтесь, впереди новая неделя и новый интересный собеседник!.
        /// </summary>
        internal static string FeedBackNoNoGoodTimeReplyText {
            get {
                return ResourceManager.GetString("FeedBackNoNoGoodTimeReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эх, но вы не огорчайтесь. Впереди новая неделя и новый интересный собеседник!.
        /// </summary>
        internal static string FeedbackNoNoResponseReplyText {
            get {
                return ResourceManager.GetString("FeedbackNoNoResponseReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за комментарий.
        /// </summary>
        internal static string FeedbackReplyAfterCommentText {
            get {
                return ResourceManager.GetString("FeedbackReplyAfterCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так себе.
        /// </summary>
        internal static string FeedBackYesAnswerBad {
            get {
                return ResourceManager.GetString("FeedBackYesAnswerBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я передумал.
        /// </summary>
        internal static string FeedBackYesAnswerCanceled {
            get {
                return ResourceManager.GetString("FeedBackYesAnswerCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошо.
        /// </summary>
        internal static string FeedBackYesAnswerGood {
            get {
                return ResourceManager.GetString("FeedBackYesAnswerGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надеюсь, я сделал правильный выбор. И как прошла ваша встреча?.
        /// </summary>
        internal static string FeedBackYesAnswerRequestText {
            get {
                return ResourceManager.GetString("FeedBackYesAnswerRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я в восторге.
        /// </summary>
        internal static string FeedBackYesAnswerVeryGood {
            get {
                return ResourceManager.GetString("FeedBackYesAnswerVeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как грустно это слышать. Поделитесь, почему?.
        /// </summary>
        internal static string FeedbackYesBadReplayText {
            get {
                return ResourceManager.GetString("FeedbackYesBadReplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здорово! Поделитесь развернутым комментарием?.
        /// </summary>
        internal static string FeedBackYesGoodReplyText1 {
            get {
                return ResourceManager.GetString("FeedBackYesGoodReplyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А впереди новая неделя и новый интересный собеседник!.
        /// </summary>
        internal static string FeedBackYesGoodReplyText2 {
            get {
                return ResourceManager.GetString("FeedBackYesGoodReplyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ура! Буду счастлив вместе с вами, если поделитесь развернутым комментарием..
        /// </summary>
        internal static string FeedbackYesSuperReplyText1 {
            get {
                return ResourceManager.GetString("FeedbackYesSuperReplyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А впереди новая неделя и новый интересный собеседник!.
        /// </summary>
        internal static string FeedbackYesSuperReplyText2 {
            get {
                return ResourceManager.GetString("FeedbackYesSuperReplyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе ты мой интересный собеседник :).
        /// </summary>
        internal static string InitMessageToRecipientText {
            get {
                return ResourceManager.GetString("InitMessageToRecipientText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошая новость! {0} добавил Random Coffee в **{1} Team.**.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с сотрудниками Dentsu Russia, и это будет взаимно :) Каждую неделю случайным образом будут определяться новые пары собеседников. Вы сможете узнать больше о людях, с которыми работаете, и найти среди них новых друзей!.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое знакомство совсем скоро! Ожидай приглашение и не упусти случай..
        /// </summary>
        internal static string InstallMessageKnownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Coffee установлен в **{0} комманду.**.
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с сотрудниками Dentsu Russia, и это будет взаимно :) Каждую неделю случайным образом будут определяться новые пары собеседников. Вы сможете узнать больше о людях, с которыми работаете, и найти среди них новых друзей!.
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое знакомство совсем скоро! Ожидай приглашение и не упусти случай..
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет снова. Это {0}, и каждую неделю я нахожу для вас нового собеседника из числа сотрудников Dentsu. А сейчас рад вам представить {2}! Еще не знакомы?.
        /// </summary>
        internal static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать общение просто: посмотрите профиль человека на портале, чтобы узнать его интересы, и скажите \&quot;Привет!\&quot;.
        /// </summary>
        internal static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы определены в пару с {0}..
        /// </summary>
        internal static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пришло время нового знакомства!.
        /// </summary>
        internal static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе {0} определил нас собеседниками :) Было бы здорово созвониться или встретиться за чашкой кофе. Искренне надеюсь на приятное времяпрепровождение..
        /// </summary>
        internal static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот и неделя прошла. {0}, я буду рад получить от вас весточку! Удалось ли вам встретиться с {1}?.
        /// </summary>
        internal static string MeetupFeedBackMsg {
            get {
                return ResourceManager.GetString("MeetupFeedBackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Встреча.
        /// </summary>
        internal static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Без тебя было скучно, но мы рады, что ты вернулся! Желаем приятных и интересных знакомств :).
        /// </summary>
        internal static string OptInConfirmation {
            get {
                return ResourceManager.GetString("OptInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знакомства с вами приостановлены. Вы можете включить их снова, когда захотите..
        /// </summary>
        internal static string OptOutConfirmation {
            get {
                return ResourceManager.GetString("OptOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить знакомства.
        /// </summary>
        internal static string PausePairingsButtonText {
            get {
                return ResourceManager.GetString("PausePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить встречу.
        /// </summary>
        internal static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возобновить знакомства.
        /// </summary>
        internal static string ResumePairingsButtonText {
            get {
                return ResourceManager.GetString("ResumePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе Random Coffee определил нас собеседниками :) Было бы здорово созвониться или встретиться за чашкой кофе. Искренне надеюсь на приятное времяпрепровождение..
        /// </summary>
        internal static string SalutationTitleText {
            get {
                return ResourceManager.GetString("SalutationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совершить экскурсию.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, не удается обработать ваше сообщение. Для ответа используйте один из предложенных выше  вариантов..
        /// </summary>
        internal static string UnknownChooseAnswerText {
            get {
                return ResourceManager.GetString("UnknownChooseAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, не удается обработать ваше сообщение. Совершите экскурсию, чтобы узнать больше о моих возможностях..
        /// </summary>
        internal static string UnrecognizedInput {
            get {
                return ResourceManager.GetString("UnrecognizedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорогой друг! Приятно видеть ваше желание принять участие в Random Coffee прямо сейчас, но пары собеседников на эту неделю уже определены. Пожалуйста, дождитесь следующего понедельника. А пока можете заполнить свой профиль на портале, чтобы коллеги узнали вас получше..
        /// </summary>
        internal static string UnregisteredUserText {
            get {
                return ResourceManager.GetString("UnregisteredUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорогой друг! Приятно, что вы помните обо мне! Я обещал вас не беспокоить и продолжаю держать свое слово. Но так хочется видеться с вами почаще. Вы готовы возобновить свое участие в Random Coffee?.
        /// </summary>
        internal static string UserIsOptedDownText {
            get {
                return ResourceManager.GetString("UserIsOptedDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть профиль.
        /// </summary>
        internal static string ViewProfileButtonText {
            get {
                return ResourceManager.GetString("ViewProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тур.
        /// </summary>
        internal static string WelcomeTourTitle {
            get {
                return ResourceManager.GetString("WelcomeTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
