//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icebreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поприветствовать {0}.
        /// </summary>
        internal static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка. Повторите попытку..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе ты мой интересный собеседник :).
        /// </summary>
        internal static string InitMessageToRecipientText {
            get {
                return ResourceManager.GetString("InitMessageToRecipientText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хорошая новость! {0} добавил Random Coffee в **{1} Team.**.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с сотрудниками Dentsu Russia, и это будет взаимно :) Каждую неделю случайным образом будут определяться новые пары собеседников. Вы сможете узнать больше о людях, с которыми работаете, и найти среди них новых друзей!.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое знакомство совсем скоро! Ожидай приглашение и не упусти случай..
        /// </summary>
        internal static string InstallMessageKnownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Coffee установлен в **{0} комманду.**.
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я помогу вам познакомиться с сотрудниками Dentsu Russia, и это будет взаимно :) Каждую неделю случайным образом будут определяться новые пары собеседников. Вы сможете узнать больше о людях, с которыми работаете, и найти среди них новых друзей!.
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новое знакомство совсем скоро! Ожидай приглашение и не упусти случай..
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет снова. Это {0}, и каждую неделю я нахожу для вас нового собеседника из числа сотрудников Dentsu. А сейчас рад вам представить {2}! Еще не знакомы?.
        /// </summary>
        internal static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать общение просто: посмотрите профиль человека на портале, чтобы узнать его интересы, и скажите &quot;Привет!&quot;.
        /// </summary>
        internal static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы определены в пару с {0}..
        /// </summary>
        internal static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пришло время нового знакомства!.
        /// </summary>
        internal static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе {0} определил нас собеседниками :) Было бы здорово созвониться или встретиться за чашкой кофе. Искренне надеюсь на приятное времяпрепровождение..
        /// </summary>
        internal static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Встреча.
        /// </summary>
        internal static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Без тебя было скучно, но мы рады, что ты вернулся! Желаем приятных и интересных знакомств :).
        /// </summary>
        internal static string OptInConfirmation {
            get {
                return ResourceManager.GetString("OptInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знакомства с вами приостановлены. Вы можете включить их снова, когда захотите..
        /// </summary>
        internal static string OptOutConfirmation {
            get {
                return ResourceManager.GetString("OptOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановить знакомства.
        /// </summary>
        internal static string PausePairingsButtonText {
            get {
                return ResourceManager.GetString("PausePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить встречу.
        /// </summary>
        internal static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возобновить знакомства.
        /// </summary>
        internal static string ResumePairingsButtonText {
            get {
                return ResourceManager.GetString("ResumePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! На этой неделе Random Coffee определил нас собеседниками :) Было бы здорово созвониться или встретиться за чашкой кофе. Искренне надеюсь на приятное времяпрепровождение..
        /// </summary>
        internal static string SalutationTitleText {
            get {
                return ResourceManager.GetString("SalutationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совершить экскурсию.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, не удается обработать ваше сообщение. Совершите экскурсию, чтобы узнать больше о моих возможностях..
        /// </summary>
        internal static string UnrecognizedInput {
            get {
                return ResourceManager.GetString("UnrecognizedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посмотреть профиль.
        /// </summary>
        internal static string ViewProfileButtonText {
            get {
                return ResourceManager.GetString("ViewProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тур.
        /// </summary>
        internal static string WelcomeTourTitle {
            get {
                return ResourceManager.GetString("WelcomeTourTitle", resourceCulture);
            }
        }
    }
}
